# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00b391b442f2654cb75e93c153818d6cc374a8ecffbf739eba1d36f0351cefca34a3e91c3fc28ad0f4b08bea43d77a97f75314f714a7e0edb94d7e1403a61cf8

test:
  secret_key_base: 5aa90990911c0fed518f7e7ab8fede1bf885c63394b00fa76f4a5091748c30daf31c95090006ce69ea220f803acb1f12fb8f44584a054f948056b97fbc0cef61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
